import { useMemo, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { Car, CircleDollarSign, Gauge, RotateCcw } from 'lucide-react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { fetchAll } from '@/lib/fetchAll';
import { useCommercial } from '@/hooks/useCommercial';
import { money, type BusinessOperation } from '@/lib/commercial';
import { Operations, OperationDialog } from './Comercial';
import { ModuleMenu } from './Estoque';
import '@/components/commercial/commercial.css';
import '@/components/commercial/commercial-overrides.css';

export default function Locacoes() {
  const location = useLocation(); const { user } = useAuth(); const queryClient = useQueryClient(); const { data, isLoading, error, refresh } = useCommercial(); const [showDialog, setShowDialog] = useState(() => new URLSearchParams(location.search).get('novo') === '1'); const [view, setView] = useState<'all' | 'active' | 'completed'>('all');
  const { data: clients = [] } = useQuery({ queryKey: ['commercial-clients', user?.id], enabled: !!user, queryFn: () => fetchAll((from, to) => supabase.from('clients').select('id,name,full_name,cpf_cnpj').eq('user_id', user!.id).order('name').range(from, to)) });
  const rentals = data.operations.filter(operation => operation.kind === 'rental'); const visibleRentals = useMemo(() => view === 'all' ? rentals : rentals.filter(operation => operation.status === view), [rentals, view]); const active = rentals.filter(operation => operation.status === 'active').length; const deposits = rentals.reduce((sum, operation) => sum + Number(operation.deposit || 0), 0); const rentalRevenue = rentals.reduce((sum, operation) => sum + Number(operation.total || 0), 0);
  const reload = async () => { await refresh(); await queryClient.invalidateQueries({ queryKey: ['commercial-clients'] }); };
  return <main className="commercial-page commercial-module-page"><ModuleMenu active={location.pathname}/><section className="commercial-hero commercial-hero-rentals"><div><span className="commercial-eyebrow"><Car size={15}/> Módulo de locações</span><h1>Alugue carros e motos com controle.</h1><p>Tenha período, cobrança, caução, quilometragem, combustível e devolução registrados em cada contrato de locação.</p></div><button className="commercial-primary" onClick={() => setShowDialog(true)}><Car size={16}/> Nova locação</button></section><section className="commercial-kpis commercial-kpis-4"><article><span>Em andamento</span><strong>{active}</strong><small>Veículos em circulação</small></article><article><span>Receita contratada</span><strong>{money(rentalRevenue)}</strong><small>Total das locações</small></article><article><span>Cauções</span><strong>{money(deposits)}</strong><small>Valores sob controle</small></article><article><span>Veículos livres</span><strong>{data.assets.filter(asset => (asset.kind === 'car' || asset.kind === 'motorcycle') && asset.status === 'available').length}</strong><small>Prontos para alugar</small></article></section><section className="commercial-panel"><div className="commercial-toolbar"><div><h2>Gestão de locações</h2><p className="commercial-muted">Acompanhe contratos ativos, datas de devolução e cauções.</p></div><div className="commercial-segmented"><button className={view === 'all' ? 'is-active' : ''} onClick={() => setView('all')}>Todas</button><button className={view === 'active' ? 'is-active' : ''} onClick={() => setView('active')}>Ativas</button><button className={view === 'completed' ? 'is-active' : ''} onClick={() => setView('completed')}>Encerradas</button></div></div>{isLoading ? <div className="commercial-empty"><h2>Carregando locações…</h2></div> : error ? <div className="commercial-empty"><h2>Não foi possível carregar as locações</h2></div> : <Operations kind="rental" assets={data.assets} operations={visibleRentals as BusinessOperation[]} receivables={data.receivables} onNew={() => setShowDialog(true)} />}</section>{showDialog && <OperationDialog kind="rental" assets={data.assets.filter(asset => (asset.kind === 'car' || asset.kind === 'motorcycle') && asset.status === 'available')} clients={clients} onClose={() => setShowDialog(false)} onSaved={reload}/>}</main>;
}
