import { useMemo, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { CircleDollarSign, Smartphone, TrendingUp, Users } from 'lucide-react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { fetchAll } from '@/lib/fetchAll';
import { useCommercial } from '@/hooks/useCommercial';
import { money, type BusinessOperation } from '@/lib/commercial';
import { Operations, OperationDialog } from './Comercial';
import { ModuleMenu } from './Estoque';
import '@/components/commercial/commercial.css';
import '@/components/commercial/commercial-overrides.css';

export default function VendasCelulares() {
  const location = useLocation(); const { user } = useAuth(); const queryClient = useQueryClient(); const { data, isLoading, error, refresh } = useCommercial(); const [showDialog, setShowDialog] = useState(() => new URLSearchParams(location.search).get('novo') === '1'); const [view, setView] = useState<'all' | 'active' | 'paid'>('all');
  const { data: clients = [] } = useQuery({ queryKey: ['commercial-clients', user?.id], enabled: !!user, queryFn: () => fetchAll((from, to) => supabase.from('clients').select('id,name,full_name,cpf_cnpj').eq('user_id', user!.id).order('name').range(from, to)) });
  const sales = data.operations.filter(operation => operation.kind === 'sale'); const visibleSales = useMemo(() => view === 'all' ? sales : sales.filter(operation => view === 'active' ? operation.status === 'active' : operation.status === 'completed'), [sales, view]); const revenue = sales.reduce((sum, operation) => sum + Number(operation.total || 0), 0); const received = data.payments.filter(payment => sales.some(operation => operation.id === payment.operation_id)).reduce((sum, payment) => sum + Number(payment.amount || 0), 0); const pending = Math.max(0, revenue - received);
  const reload = async () => { await refresh(); await queryClient.invalidateQueries({ queryKey: ['commercial-clients'] }); };
  return <main className="commercial-page commercial-module-page"><ModuleMenu active={location.pathname}/><section className="commercial-hero commercial-hero-sales"><div><span className="commercial-eyebrow"><Smartphone size={15}/> Módulo de vendas</span><h1>Venda celulares com clareza.</h1><p>Associe cada venda ao cliente e ao IMEI, organize a entrada, as parcelas e o recebimento em um único fluxo.</p></div><button className="commercial-primary" onClick={() => setShowDialog(true)}><CircleDollarSign size={16}/> Registrar venda</button></section><section className="commercial-kpis commercial-kpis-4"><article><span>Vendas registradas</span><strong>{sales.length}</strong><small>Operações de celulares</small></article><article><span>Faturamento</span><strong>{money(revenue)}</strong><small>Valor total vendido</small></article><article><span>Recebido</span><strong>{money(received)}</strong><small>Pagamentos confirmados</small></article><article><span>Em aberto</span><strong>{money(pending)}</strong><small>Parcelas pendentes</small></article></section><section className="commercial-panel"><div className="commercial-toolbar"><div><h2>Gestão de vendas</h2><p className="commercial-muted">Acompanhe clientes, celulares, situação e saldo de cada operação.</p></div><div className="commercial-segmented"><button className={view === 'all' ? 'is-active' : ''} onClick={() => setView('all')}>Todas</button><button className={view === 'active' ? 'is-active' : ''} onClick={() => setView('active')}>Em andamento</button><button className={view === 'paid' ? 'is-active' : ''} onClick={() => setView('paid')}>Concluídas</button></div></div>{isLoading ? <div className="commercial-empty"><h2>Carregando vendas…</h2></div> : error ? <div className="commercial-empty"><h2>Não foi possível carregar as vendas</h2></div> : <Operations kind="sale" assets={data.assets} operations={visibleSales as BusinessOperation[]} receivables={data.receivables} onNew={() => setShowDialog(true)} />}</section>{showDialog && <OperationDialog kind="sale" assets={data.assets.filter(asset => asset.kind === 'phone' && asset.status === 'available')} clients={clients} onClose={() => setShowDialog(false)} onSaved={reload}/>}</main>;
}
